### ISSUE TITLE
Cannot make it work here!

### ISSUE THREAD

**Issue by caramujoneto** [syxanash/TODOWidget#1]
Hello man! I've benn using geektools for years! But started using reminds this year. So, here i go chasing a good geeklet to put my reminders on my desktop. I installed the reminders-cli and just launched you geeklet, but nothing shows up! I must be doing something wrong. Can you please help me?

**Comment by syxanash** [comment]
Hey dude thanks for letting me know I've updated the Regex on line 57 it should work now!
Make sure you install the CPAN dependencies for the Perl script to work with the following commands:
```
sudo perl -MCPAN -e 'install IPC::System::Simple'
```
and
```
sudo perl -MCPAN -e 'install Readonly'
```

**Comment by caramujoneto** [comment]
First of all: thanks for your work dude! 

Maybe I am too newbie for this, probably did something wrong on the reminders-cli instalation. I did it through homebrew 
(I've installed homebrew with the terminal, and than installed the reminders-cli on the same tab). For last I tried to open you first geeklet.  

Now I've runned those commands on terminal and tried to open the new geeklet. But nothing =(

I don't wanna be a trouble to you. But if you can help me I would be eternally grateful! Once: thanks for you attention! 
![Captura de Tela 2021-04-28 às 11 07 13](https://user-images.githubusercontent.com/83318870/116419072-12e87000-a813-11eb-8296-166b720ea8a1.png)

**Comment by syxanash** [comment]
the geeklet configuration looks good same as the reminders-cli installation from what you wrote.
I think you now have to open the terminal and install those two Perl libraries I mentioned in my previous comment. The libs are needed to run the Perl script geeklet uses to parse the items from Reminders app.

If the two libraries have been correctly installed you should be able to run the script  in the `bin/` folder called `reminder.pl` using the following command `perl reminder.pl` and this should be the output:
```
,--------------------------------------------------,
| [?] TODO list:                                   |
| - buy chicken                                    |
| - sell NFTs                                      |
`--------------------------------------------------´
```

**Comment by syxanash** [comment]
closing the issue let me know if you have other issues.
