### ISSUE TITLE
Script Timed Out

### ISSUE THREAD

**Issue by caramujoneto** [syxanash/TODOWidget#2]
![Captura de Tela 2021-05-12 às 12 50 32](https://user-images.githubusercontent.com/83318870/118006088-58cc2a80-b321-11eb-8201-dfd3f1a92df3.png)

 Hey man, me again! Having this issue in geek tools! I have no idea if it is about reminders-cli or you winged. Did it happened to you?

**Comment by caramujoneto** [comment]
issue resolved! Just restarted the computer! Thanks!

**Comment by syxanash** [comment]
glad you made it work ;)
